# Generated by Django 3.2.7 on 2021-11-17 07:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vaccine',
            old_name='vaccine_name',
            new_name='brand_name',
        ),
        migrations.RenameField(
            model_name='vaccine',
            old_name='title',
            new_name='vaccine',
        ),
        migrations.RemoveField(
            model_name='growth',
            name='patient_name',
        ),
        migrations.AddField(
            model_name='vaccine',
            name='date_given',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
