# Generated by Django 3.2.7 on 2021-11-17 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20211117_1034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='growth',
            name='patient_name',
        ),
    ]
