# Generated by Django 3.2.7 on 2021-11-18 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_vaccine_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaccine',
            name='link',
        ),
        migrations.RemoveField(
            model_name='vaccine',
            name='brand_name',
        ),
        migrations.AddField(
            model_name='vaccine',
            name='brand_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
