# Generated by Django 3.2.7 on 2021-11-18 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20211119_0120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='growth',
            name='link',
        ),
    ]
