# Generated by Django 3.2.7 on 2021-11-13 15:15

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import url_or_relative_url_field.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0004_auto_20211103_1753'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vaccine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('batch_number', models.DecimalField(decimal_places=2, max_digits=12)),
                ('drug_expiry', models.TextField()),
                ('user_profile', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('next_appointment', models.CharField(max_length=50)),
                ('link', url_or_relative_url_field.fields.URLOrRelativeURLField()),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vaccines', to='app.category')),
            ],
        ),
        migrations.RemoveField(
            model_name='cart',
            name='product',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.AddField(
            model_name='vaccine',
            name='vaccine_name',
            field=models.ManyToManyField(through='app.Cart', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cart',
            name='vaccine',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.vaccine'),
            preserve_default=False,
        ),
    ]
