# Generated by Django 3.2.7 on 2021-11-14 21:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import url_or_relative_url_field.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0007_auto_20211114_2321'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emergingdisease',
            old_name='desiease_name',
            new_name='disease_name',
        ),
        migrations.CreateModel(
            name='Growth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('height', models.IntegerField()),
                ('HO', models.IntegerField()),
                ('date', models.DateField()),
                ('link', url_or_relative_url_field.fields.URLOrRelativeURLField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
